// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWyFX6OLFreUMLCVqqdlZsayd3YdJOOqM',
    appId: '1:943324468470:web:3acf067da32dc0484108d7',
    messagingSenderId: '943324468470',
    projectId: 'questionaire-app-qizo',
    authDomain: 'questionaire-app-qizo.firebaseapp.com',
    storageBucket: 'questionaire-app-qizo.appspot.com',
    measurementId: 'G-591Y3VTGF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXuFhvuw6teejGULmv2RNN1xO-7W7No80',
    appId: '1:943324468470:android:361df451a86812954108d7',
    messagingSenderId: '943324468470',
    projectId: 'questionaire-app-qizo',
    storageBucket: 'questionaire-app-qizo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDuoERXWlvijvjDxMAWOYY83R7O5JLIV8',
    appId: '1:943324468470:ios:964cb9bcd363649c4108d7',
    messagingSenderId: '943324468470',
    projectId: 'questionaire-app-qizo',
    storageBucket: 'questionaire-app-qizo.appspot.com',
    iosClientId: '943324468470-16ei77hncmm804v3v1kmd8l5hdsat7mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.questanaireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDuoERXWlvijvjDxMAWOYY83R7O5JLIV8',
    appId: '1:943324468470:ios:afd963f296eba0ca4108d7',
    messagingSenderId: '943324468470',
    projectId: 'questionaire-app-qizo',
    storageBucket: 'questionaire-app-qizo.appspot.com',
    iosClientId: '943324468470-j8bcj77lfp4imn3brigkakojlfehgjkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.questanaireApp.RunnerTests',
  );
}
